version: 0.2

phases:
    install:
      commands:
            - echo "Trying"
      pre_build:
          commands:
            - echo "pre build phase"
      build:
          commands:
            - echo "some test"

